export const dummySkills: SkillRecord[] = [
	{
		id: "skill-1",
		title: "React",
		slug: "react",
		description: "A JavaScript library for building user interfaces.",
		category: "Frontend",
		tags: ["javascript", "ui", "web"],
		installCommand: "npm install react react-dom",
		createdAt: "2024-01-15T10:00:00.000Z",
		authorClerkId: null,
		authorEmail: "alice@example.com",
	},
	{
		id: "skill-2",
		title: "Node.js",
		slug: "nodejs",
		description: "JavaScript runtime built on Chrome's V8 engine.",
		category: "Backend",
		tags: ["javascript", "server", "runtime"],
		installCommand: "nvm install --lts && npm init -y",
		createdAt: "2023-11-02T08:30:00.000Z",
		authorClerkId: null,
		authorEmail: "bob@example.com",
	},
	{
		id: "skill-3",
		title: "Docker",
		slug: "docker",
		description: "Containerization platform for packaging applications.",
		category: "DevOps",
		tags: ["containers", "deployment"],
		installCommand: "https://docs.docker.com/get-docker/",
		createdAt: "2022-06-20T12:00:00.000Z",
		authorClerkId: null,
		authorEmail: null,
	},
	{
		id: "skill-4",
		title: "PostgreSQL",
		slug: "postgresql",
		description: "Powerful, open source object-relational database system.",
		category: "Data",
		tags: ["database", "sql"],
		installCommand: "sudo apt-get install postgresql",
		createdAt: "2021-09-10T09:15:00.000Z",
		authorClerkId: null,
		authorEmail: "carol@example.com",
	},
	{
		id: "skill-5",
		title: "Vite",
		slug: "vite",
		description: "Next generation frontend tooling for fast development.",
		category: "Tooling",
		tags: ["build", "frontend", "bundler"],
		installCommand: "npm create vite@latest",
		createdAt: null,
		authorClerkId: null,
		authorEmail: null,
	},
];

export default dummySkills;
